[ddaily_parkhyunyoung]
title = "디지털데일리 ─ 박현영 기자"
url = "https://www.ddaily.co.kr/news/article_list_writer.html?name=%EB%B0%95%ED%98%84%EC%98%81"
entrySelector = "div.m01_ara dl"
titleSelector = "dt a"
linkSelector = "dd a"
contentSelector = "dd a"
waitUntil = "networkidle"